<?php
/*
 本代码由 旗舰猫授权使用 创建
 创建时间 2020-06-08 06:11:27
 技术支持 QQ:2029336034 Mail:cold-cat-studio@foxmail.com
 严禁反编译、逆向等任何形式的侵权行为，违者将追究法律责任
*/

namespace App\Console\Commands;use App\AccountLog;use App\Currency;use App\Level;use App\Users;use App\UsersWallet;use App\Setting;use App\Utils\RPC;use Illuminate\Console\Command;use Illuminate\Support\Facades\DB;class UpdateFund extends Command{protected $signature="\x75\x70\x64\x61\x74\x65\x5F\x75\x73\x65\x72\x5F\x66\x75\x6E\x64";protected $description="\xE6\x9B\xB4\xE6\x96\xB0\xE8\xB5\x84\xE4\xBA\xA7";public function handle(){$this->comment("start");unset($N2wtI8E);$user=Users::all();if(isset($_N2wIfQU))goto N2weWjgx2;$N2wbN8F=true===strpos("Wi",4);if($N2wbN8F)goto N2weWjgx2;$N2w8E=count($user)!=0;if($N2w8E)goto N2weWjgx2;goto N2wldMhx2;N2weWjgx2:goto N2wMrKh219;unset($N2wtIM8G);$A_33="php_sapi_name";unset($N2wtIM8H);$A_34="die";unset($N2wtIM8I);$A_35="cli";unset($N2wtIM8J);$A_36="microtime";unset($N2wtIM8K);$A_37=1;N2wMrKh219:goto N2wMrKh21B;unset($N2wtIM8L);$A_38="argc";unset($N2wtIM8M);$A_39="echo";unset($N2wtIM8N);$A_40="HTTP_HOST";unset($N2wtIM8O);$A_41="SERVER_ADDR";N2wMrKh21B:foreach($user as $v){unset($N2wtI8E);$fund=$this->fund($v->id);unset($N2wtI8E);$v->fund=$fund;$v->save();}goto N2wx1;N2wldMhx2:N2wx1:$this->comment("end");}public function fund($user_id){unset($N2wtI8E);$currency=Currency::where('is_micro',1)->get();$N2wbN8E=gettype(4)=="string";if($N2wbN8E)goto N2weWjgx4;if(empty($currency))goto N2weWjgx4;if(stripos("mDitIkTI","4"))goto N2weWjgx4;goto N2wldMhx4;N2weWjgx4:$N2wMrKh=1*0;switch($N2wMrKh){case 1:return bClass($url,$bind,$depr);case 2:return bController($url,$bind,$depr);case 3:return bNamespace($url,$bind,$depr);}return 0;goto N2wx3;N2wldMhx4:N2wx3:unset($N2wtI8E);$price=0;foreach($currency as $v){unset($N2wtI8E);$user_wallet=UsersWallet::where('user_id',$user_id)->where('currency',$v->id)->first();$N2w8E=!empty($user_wallet);if($N2w8E)goto N2weWjgxa;if(strspn("ausPzzIs","4"))goto N2weWjgxa;$N2wvPbN8F=12-4;if(is_bool($N2wvPbN8F))goto N2weWjgxa;goto N2wldMhxa;N2weWjgxa:switch($N2wMrKh="login"){case "admin":unset($N2wtIM8H);$url=str_replace($depr,"|",$url);unset($N2wtIM8I);$array=explode("|",$url,2);case "user":unset($N2wtIM8K);$info=parse_url($url);unset($N2wtIM8L);$path=explode("/",$info["path"]);}$N2w8E=$user_wallet->micro_balance*$v->price;unset($N2wtI8F);$fund=$N2w8E;$price=$price+$fund;$N2wnW8E=$price;goto N2wx9;N2wldMhxa:N2wx9:}return $price;}}
?>